---
output: 
  md_document:
    variant: markdown_github
---


```{r setup, echo=FALSE, results='hide'}
#Loading packages
library(tidyverse)
library(viridis)

#Load data
df <- read_csv("us-counties.csv") %>% 
  filter(state == "Washington",
         county != "Unknown") %>% 
  select(-c(fips, state))

covid_19 <- df %>% 
  group_by(date) %>% 
  summarise(cases = sum(cases),
            deaths = sum(deaths)) %>%
  mutate(county = "Aggregate") %>% 
  bind_rows(df)

knitr::opts_chunk$set(
	fig.height = 10,
	fig.width = 9,
	message = FALSE,
	warning = FALSE
)
```



```{r graphic}
ggplot(covid_19, aes(date, fct_reorder(county, date), fill = log(cases))) +
  geom_tile(colour = "white") +
  scale_fill_viridis(name = "Num. of \nCases \n(log)",
                     guide = guide_colourbar(direction = "horizontal"),
                     option = "magma") +
  labs(
    x = "Date",
    y = "Washington County",
    title = "Timeline of COVID-19 Caes by Washington County"
  ) +
  theme(
    axis.text  = element_text(size = 12),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    plot.title = element_text(size = 18),
    legend.position = "bottom"
  )

```


